### ISSUE TITLE
Perhaps increase max size of attached images?

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#220]
1 Mb is not very much, both if people use pictures they have taken, flyers in picture format or often pictures from the web too. I guess people would drop it, rather than try to find out how to resize them.

I'd suggest to increase the limit to fx 3mb, or to include an automatic resizer on the page, as I have seen somewhere else...

**Comment by ronan-mch** [comment]
Somewhere else with a bigger development budget than we have I guess ;) 
But yeah, this has been mentioned before and it's not actually a big 
deal. What I do is I put in some client side validation to make sure the 
file looks okay and then when it gets uploaded I create two copies, a 
thumbnail for the front page and a medium size for the event page. So 
I'm actually not saving the original file in order to avoid filling up 
my disk. The only reason for putting a limit of 1 meg on the upload is 
that I'm a bit worried of someone using this as a DDOS vector, i.e. 
sending large files which the server will have to handle. But I'm 
probably just being paranoid. I'll up it to 3 as you suggest.

**Comment by ronan-mch** [comment]
Fixed.

**Comment by Siggik** [comment]
Jeg mindes at det et sted var snak om at gøre thumbnailene på forsiden større. Det er hvis ikke her, men i hvert fald. Det kunne være nice hvis de blev lidt større, så de mere passede med størrelsen på event-teksten:)
