### ISSUE TITLE
Cannot create recurring events beyond a year change

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#223]
I try to create a Folkets Haus recurring event. I make the whole thing and it says that it has been created with "0 forekomster". I had set it to be friday, the second week in the month, from november 13th to january 8th.

Bug or my mistake?

Last tried at 16:31

**Comment by ronan-mch** [comment]
I dunno, :confused: I'll check it out.

**Comment by ronan-mch** [comment]
It's not you, it's me. Definitely a bug. Working on it.

tor. 8. okt. 2015 16.35 skrev tadoh <notifications@github.com>:

**Comment by ronan-mch** [comment]
Ha! It's because you set the expiry til January. It's using the numbers for
the months to create a range and since there is no range between 10 and 1
it's not able to do it. If you do it until December it works fine. Feck. I
think I remember considering that briefly when I was coding before
forgetting about it. But yeah, it's a serious bug and I will have to fix
it. I'm a bit busy with family stuff at the moment but I'll try and get it
done next week.

**Comment by tadoh** [comment]
Nice. I like the "I got it!" sound of your reply :)

**Comment by ronan-mch** [comment]
Hi bunny, the fix is made and deployed to staging (thawing-dawn bla bla). I made a test event with the same parameters and it worked fine. If you could test it please and sign off, I will deploy it to prod (dukop.dk) over the weekend. Lots of love, the masked man.

**Comment by tadoh** [comment]
Jeps - it works :+1: 
Nice job :)

**Comment by tadoh** [comment]
Ups, dunno if I was supposed to close it...?
